### ISSUE TITLE
Unknown "getVars" function

### ISSUE THREAD

**Issue by TechFanDan** [cakephp/TwigView#228]
When I attempt to run `{% do getVars()|debug %}` in my twig file, I get the following error: 

> Exception: Unknown "getVars" function. in [/path/to/app/plugins/MyPlugin/src/Template/Bake//Model/entity.twig, line 17]

`entity.twig`

Line 17: {% do getVars()|debug %}

Here is the full trace:

```
$ ./cake bake model all -t MyPlugin
One moment while associations are detected.

Baking table class for CommitmentItems...

File `/path/to/app/src/Model/Table/CommitmentItemsTable.php` exists
Do you want to overwrite? (y/n/a/q)
[n] > a
Wrote `/path/to/app/src/Model/Table/CommitmentItemsTable.php`
Exception: Unknown "getVars" function. in [/path/to/app/plugins/MyPlugin/src/Template/Bake//Model/entity.twig, line 17]
2019-12-19 15:28:16 Error: [Twig\Error\SyntaxError] Unknown "getVars" function. in /path/to/app/plugins/MyPlugin/src/Template/Bake//Model/entity.twig on line 17
Stack Trace:
#0 /path/to/app/vendor/twig/twig/src/ExpressionParser.php(461): Twig\ExpressionParser->getFunctionNodeClass('getVars', 17)
#1 /path/to/app/vendor/twig/twig/src/ExpressionParser.php(243): Twig\ExpressionParser->getFunctionNode('getVars', 17)
#2 /path/to/app/vendor/twig/twig/src/ExpressionParser.php(183): Twig\ExpressionParser->parsePrimaryExpression()
#3 /path/to/app/vendor/twig/twig/src/ExpressionParser.php(78): Twig\ExpressionParser->getPrimary()
#4 /path/to/app/vendor/twig/twig/src/TokenParser/DoTokenParser.php(26): Twig\ExpressionParser->parseExpression()
#5 /path/to/app/vendor/twig/twig/src/Parser.php(209): Twig\TokenParser\DoTokenParser->parse(Object(Twig\Token))
#6 /path/to/app/vendor/twig/twig/src/Parser.php(122): Twig\Parser->subparse(NULL, false)
#7 /path/to/app/vendor/twig/twig/src/Environment.php(735): Twig\Parser->parse(Object(Twig\TokenStream))
#8 /path/to/app/vendor/twig/twig/src/Environment.php(793): Twig\Environment->parse(Object(Twig\TokenStream))
#9 /path/to/app/vendor/twig/twig/src/Environment.php(482): Twig\Environment->compileSource(Object(Twig\Source))
#10 /path/to/app/vendor/twig/twig/src/Environment.php(445): Twig\Environment->loadClass('__TwigTemplate_...', '/srv/www/htdocs...', NULL)
#11 /path/to/app/vendor/wyrihaximus/twig-view/src/View/TwigView.php(180): Twig\Environment->loadTemplate('/srv/www/htdocs...')
#12 /path/to/app/vendor/cakephp/bake/src/View/BakeView.php(146): WyriHaximus\TwigView\View\TwigView->_render('/srv/www/htdocs...')
#13 /path/to/app/vendor/cakephp/bake/src/Shell/Task/BakeTemplateTask.php(91): Bake\View\BakeView->render('Model/entity')
#14 /path/to/app/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(968): Bake\Shell\Task\BakeTemplateTask->generate('Model/entity')
#15 /path/to/app/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(116): Bake\Shell\Task\ModelTask->bakeEntity(Object(App\Model\Table\CommitmentItemsTable), Array)
#16 /path/to/app/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(101): Bake\Shell\Task\ModelTask->bake('CommitmentItems')
#17 /path/to/app/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(171): Bake\Shell\Task\ModelTask->main('commitment_item...')
#18 /path/to/app/vendor/cakephp/cakephp/src/Console/Shell.php(517): Bake\Shell\Task\ModelTask->all()
#19 /path/to/app/vendor/cakephp/cakephp/src/Console/Shell.php(524): Cake\Console\Shell->runCommand(Array, false, Array)
#20 /path/to/app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(385): Cake\Console\Shell->runCommand(Array, true)
#21 /path/to/app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(162): Cake\Console\CommandRunner->runShell(Object(Bake\Shell\BakeShell), Array)
#22 /path/to/app/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#23 {main}
```

**Comment by WyriHaximus** [comment]
Did you add `getVars` through an extension? as Twig is only aware of functions you tell it about.

**Comment by TechFanDan** [comment]
As I'm unfamiliar with what you are proposing, I'm going to have to say no :)

ATM, I'm simply trying to modify my bake templates. I'm attempting to use available variables to accomplish this. The getVars was supposed to tell me what is available and to see what else I needed.

**Comment by ndm2** [comment]
`getVars()` is a function provided by https://github.com/WyriHaximus/TwigView/blob/a5ec66690aa045d6eda17ab1c8a5baf0efdcfa45/src/Lib/Twig/Extension/View.php#L51-L53

but the extension is missing in https://github.com/WyriHaximus/TwigView/blob/a5ec66690aa045d6eda17ab1c8a5baf0efdcfa45/src/Event/ExtensionsListener.php#L64-L73

**Comment by TechFanDan** [comment]
FWIW, I attempted to load the missing extension View. However, it seems the constructor requires a CakeView parameter which is missing and throwing an error.

**Comment by ndm2** [comment]
```php
$event->getTwig()->addExtension(new Extension\View($event->getTwigView()));
```

**Comment by TechFanDan** [comment]
That works, no more errors. From the variables listed, I'm not seeing what I need. That's for another day :)
